// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemGestionHR.Data;

#nullable disable

namespace SystemGestionHR.Data.Migrations
{
    [DbContext(typeof(EmployeDB))]
    [Migration("20230315190326_intialDB")]
    partial class intialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SystemGestionHR.Data.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Nom = "Male"
                        },
                        new
                        {
                            GenreId = 2,
                            Nom = "Female"
                        });
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Nom = "Employee"
                        },
                        new
                        {
                            RoleId = 2,
                            Nom = "HR Manger"
                        });
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Employe", b =>
                {
                    b.Property<int>("EmployeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeId");

                    b.HasIndex("GenreId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employes");
                });


            modelBuilder.Entity("SystemGestionHR.Data.Models.DemandeDeConge", b =>
                {
                    b.Property<int>("DemandeDeCongeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeCongeId")
                        .HasColumnType("int");

                    b.HasKey("DemandeDeCongeId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("TypeCongeId");

                    b.ToTable("DemandeDeConge");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.TypeConge", b =>
                {
                    b.Property<int>("TypeCongeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ValeurInitiale")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TypeCongeId");

                    b.ToTable("TypeConge");

                    b.HasData(
                       new
                       {
                           TypeCongeId = 1,
                           ValeurInitiale = 7,
                           Nom = "Vacances"
                       },
                       new
                       {
                           TypeCongeId = 2,
                           ValeurInitiale = 14,
                           Nom = "Maladie"
                       },
                       new
                       {
                           TypeCongeId = 3,
                           ValeurInitiale = 7,
                           Nom = "Casual"
                       },
                       new
                       {
                           TypeCongeId = 4,
                           ValeurInitiale = 14,
                           Nom = "Schedule"
                       },
                       new
                       {
                           TypeCongeId = 5,
                           ValeurInitiale = 14,
                           Nom = "Autre"
                       });
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Employe", b =>
                {
                    b.HasOne("SystemGestionHR.Data.Models.Genre", "Genre")
                        .WithMany("Users")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemGestionHR.Data.Models.Role", "Role")
                        .WithMany("Employes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.DemandeDeConge", b =>
                {
                    b.HasOne("SystemGestionHR.Data.Models.Employe", "Employe")
                        .WithMany("DemandeDeConge")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemGestionHR.Data.Models.TypeConge", "TypeConge")
                        .WithMany("TypeConge")
                        .HasForeignKey("Type¨CongeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("TypeConge");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Genre", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Role", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("SystemGestionHR.Data.TypeConge", b =>
                {
                    b.Navigation("DemandesDeConge");
                });
#pragma warning restore 612, 618
        }
    }
}
