// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SystemGestionHR.Data.Migrations
{
    [DbContext(typeof(EmployeDB))]
    partial class EmployeeDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SystemGestionHR.Data.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Nom = "Masculin"
                        },
                        new
                        {
                            GenreId = 2,
                            Nom = "Féminin"
                        });
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Nom = "Employe"
                        },
                        new
                        {
                            RoleId = 2,
                            Nom = "HR Manger"
                        });
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Employe", b =>
                {
                    b.Property<int>("EmployeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeId"));

                    b.Property<DateTime>("DateNaissante")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeId");

                    b.HasIndex("GenreId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.DemandeDeConge", b =>
                {
                    b.Property<int>("DemandeCongeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DemandeCongeId"));

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeCongeId")
                        .HasColumnType("integer");
                    b.Property<string>("CommentaireManager")
                       .IsRequired()
                       .HasMaxLength(250)
                       .HasColumnType("character varying(250)");
                    b.Property<string>("commentaireEmploye")
                       .IsRequired()
                       .HasMaxLength(250)
                       .HasColumnType("character varying(250)");

                    b.HasKey("DemandeCongeId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("TypeCongeId");

                    b.ToTable("DemandeDeConge");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.TypeConge", b =>
                {
                    b.Property<int>("TypeCongeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeCongeId"));

                    b.Property<int>("ValeurInitiale")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TypeCongeId");

                    b.ToTable("TypeConge");

                    b.HasData(
                        new
                        {
                            TypeCongeId = 1,
                            ValeurInitiale = 7,
                            Nom = "Vacances"
                        },
                        new
                        {
                            TypeCongeId = 2,
                            ValeurInitiale = 14,
                            Nom = "Maladie"
                        },
                         new
                         {
                             TypeCongeId = 3,
                            ValeurInitiale = 7,
                             Nom = "Personnel"
                         },
                          new
                          {
                              TypeCongeId = 4,
                              ValeurInitiale = 7,
                              Nom = "Schedule"
                          },
                        new
                        {
                            TypeCongeId = 5,
                            ValeurInitiale = 14,
                            Nom = "Autre"
                        });
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Employe", b =>
                {
                    b.HasOne("SystemGestionHR.Data.Models.Genre", "Genre")
                        .WithMany("Employes")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemGestionHR.Data.Models.Role", "Role")
                        .WithMany("Employes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Role");
                });


            modelBuilder.Entity("SystemGestionHR.Data.Models.DemandeDeConge", b =>
                {
                    b.HasOne("SystemGestionHR.Data.Models.Employe", "Employe")
                        .WithMany("DemandeDeConge")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemGestionHR.Data.Models.TypeConge", "TypeConge")
                        .WithMany("DemandeDeConge")
                        .HasForeignKey("TypeCongeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("TypeConge");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Genre", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Role", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.Employe", b =>
                {
                    b.Navigation("DemandesConge");
                });

            modelBuilder.Entity("SystemGestionHR.Data.Models.TypeConge", b =>
                {
                    b.Navigation("DemandesConge");
                });
#pragma warning restore 612, 618
        }
    }
}
